### ISSUE TITLE
get_current_playercount

### ISSUE THREAD

**Issue by madlifer** [mrkaland95/SeedingScript#3]
![image](https://github.com/user-attachments/assets/f55efda7-ef53-4b2f-a783-5d7ba46698a7)

Since version 7.2, Squad no longer uses Steam's server list service and has moved to Epic. Is it still possible to query the number of people on the server?

**Comment by madlifer** [comment]
A2s is for steam right?
![image](https://github.com/user-attachments/assets/7682907b-9d9b-4043-a88b-f61491ea5b32)

**Comment by mrkaland95** [comment]
> A2s is for steam right? ![image](https://private-user-images.githubusercontent.com/28928374/356256733-7682907b-9d9b-4043-a88b-f61491ea5b32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzYwNTksIm5iZiI6MTcyMzEzNTc1OSwicGF0aCI6Ii8yODkyODM3NC8zNTYyNTY3MzMtNzY4MjkwN2ItOWQ5Yi00MDQzLWE4OGItZjYxNDkxZWE1YjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE2NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZDI0YzlhYTI3NWNkOTIwZTM4NzA3ZGIzMWI0NzA0NDE4YzM2ZGFiZmQ0MjgxNWUxYjYyZmI0YTRkMDJlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPBv0u31ceerhDgvRuKIz6Q2qQmP3uXxfHfwlzoVbF4)

Yes, A2s is for Steam. I'm not currently aware of any public methods of querying a server for player numbers. You can do it via RCON, but that obviously requires credentials you don't want to expose to the public.

**Comment by mrkaland95** [comment]
It's slightly hacky and stupid, and does require you to have access to RCON credentials of the server you're trying to use this script on, but i did write a small webserver that works as a middleman to expose that data again.

It's this one here.

https://github.com/mrkaland95/SquadInfoServer

**Comment by madlifer** [comment]
I actually need a public way to get current player count. 

Cause I think many players have a problem if they want into a particular server.  the waitlist, you knows. too fxxking long.

if I can get current player count, I will make a favorite server list （game outside apps）,people can see which server is good time to join.

I know the gamer can watch themselves server collection in game, but believe me,  outside apps is a better way. :)

**Comment by mrkaland95** [comment]
> I actually need a public way to get current player count.
> 
> Cause I think many players have a problem if they want into a particular server. the waitlist, you knows. too fxxking long.
> 
> if I can get current player count, I will make a favorite server list （game outside apps）,people can see which server is good time to join.
> 
> I know the gamer can watch themselves server collection in game, but believe me, outside apps is a better way. :)

Well that's what i'm saying, as far as i am aware, there is no equivalent, publically available way to retrieve player numbers like A2S in the EOS backend. As a workaround i wrote that webserver to act as a proxy so that data can be publically available. Of course, you would have to be a server owner for it to really work for you. If you're not, i'm afraid you're probably out of luck for the time being.

But it does work fine, for example:

https://tt-roles.tacticaltriggernometry.com/api/playercount

Granted, that doesen't solve the problem you're talking about, so on that front i'm afraid i can't help.

**Comment by madlifer** [comment]
> Well that's what i'm saying, as far as i am aware, there is no equivalent, publically available way to retrieve player numbers like A2S in the EOS backend. As a workaround i wrote that webserver to act as a proxy so that data can be publically available. Of course, you would have to be a server owner for it to really work for you. If you're not, i'm afraid you're probably out of luck for the time being.好吧，这就是我所说的，据我所知，没有等效的，可替代的方式来检索玩家号码，如A2S在EOS后端。作为一种变通方法，我编写了Web服务器作为代理，以便数据可以在网络上可用。当然，你必须是一个服务器所有者，它才能真正为你工作。如果你没有，恐怕你暂时运气不好。
> 
> But it does work fine, for example:但它确实工作得很好，例如：
> 
> https://tt-roles.tacticaltriggernometry.com/api/playercount
> 
> Granted, that doesen't solve the problem you're talking about, so on that front i'm afraid i can't help.当然，这并不能解决你所说的问题，所以在这方面我恐怕帮不上忙。

anyway， thanks for your patient and sincere response. have a good day！

**Comment by madlifer** [comment]
> > I actually need a public way to get current player count.实际上我需要一个公开的方式来获得当前的玩家数量。
> > Cause I think many players have a problem if they want into a particular server. the waitlist, you knows. too fxxking long.因为我认为很多玩家如果想进入某个特定的服务器会有问题。候补名单你知道的太他妈久了
> > if I can get current player count, I will make a favorite server list （game outside apps）,people can see which server is good time to join.如果我能得到当前玩家数量，我会做一个最喜欢的服务器列表（应用程序外的游戏），人们可以看到哪个服务器是加入的好时机。
> > I know the gamer can watch themselves server collection in game, but believe me, outside apps is a better way. :)我知道玩家可以在游戏中观看自己的服务器收集，但相信我，外部应用程序是一个更好的方法。:)
> 
> Well that's what i'm saying, as far as i am aware, there is no equivalent, publically available way to retrieve player numbers like A2S in the EOS backend. As a workaround i wrote that webserver to act as a proxy so that data can be publically available. Of course, you would have to be a server owner for it to really work for you. If you're not, i'm afraid you're probably out of luck for the time being.好吧，这就是我所说的，据我所知，没有等效的，可替代的方式来检索玩家号码，如A2S在EOS后端。作为一种变通方法，我编写了Web服务器作为代理，以便数据可以在网络上可用。当然，你必须是一个服务器所有者，它才能真正为你工作。如果你不是，恐怕你暂时可能运气不佳。
> 
> But it does work fine, for example:但它确实工作得很好，例如：
> 
> https://tt-roles.tacticaltriggernometry.com/api/playercount
> 
> Granted, that doesen't solve the problem you're talking about, so on that front i'm afraid i can't help.当然，这并不能解决你所说的问题，所以在这方面我恐怕帮不上忙。

Can you add my Discord？ I want your help and may not talk in public. 

https://discord.com/users/1146702319661101076
